package com.youmeek.ssm.module.job.mapper;

import com.youmeek.ssm.module.job.pojo.JobInfo;

import java.util.List;

public interface JobInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer jobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_info
     *
     * @mbggenerated
     */
    int insert(JobInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_info
     *
     * @mbggenerated
     */
    int insertSelective(JobInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_info
     *
     * @mbggenerated
     */
    JobInfo selectByPrimaryKey(Integer jobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(JobInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(JobInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(JobInfo record);


    /**
     * @param name
     * @return
     */
    List<JobInfo> selectByUserName(String name);
}