package com.youmeek.ssm.module.doc.mapper;

import com.youmeek.ssm.module.doc.pojo.DocumentInfo;

import java.util.List;

public interface DocumentInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long docId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_info
     *
     * @mbggenerated
     */
    int insert(DocumentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_info
     *
     * @mbggenerated
     */
    int insertSelective(DocumentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_info
     *
     * @mbggenerated
     */
    DocumentInfo selectByPrimaryKey(Long docId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DocumentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(DocumentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DocumentInfo record);

    /**
     * @param jobID
     * @return
     */
    List<DocumentInfo> selectByJobID(Integer jobID);
}