package com.youmeek.ssm.module.esindex.mapper;

import com.youmeek.ssm.module.esindex.pojo.EsIndex;

import java.util.List;

public interface EsIndexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_index
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer indexId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_index
     *
     * @mbggenerated
     */
    int insert(EsIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_index
     *
     * @mbggenerated
     */
    int insertSelective(EsIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_index
     *
     * @mbggenerated
     */
    EsIndex selectByPrimaryKey(Integer indexId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_index
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EsIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_index
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(EsIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_index
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EsIndex record);

    /**
     * @return
     */
    List<EsIndex> selectAll();

}