/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.youmeek.ssm.module.query.service;

public class datatypeConstants {

  public static final String VERSION = "1.0.0";

}
