/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.youmeek.ssm.module.rpc;


import org.apache.thrift.TEnum;

public enum Action implements TEnum {
  QUERY(0),
  INSERT(1),
  UPDATE(2),
  DELETE(3);

  private final int value;

  private Action(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Action findByValue(int value) {
    switch (value) {
      case 0:
        return QUERY;
      case 1:
        return INSERT;
      case 2:
        return UPDATE;
      case 3:
        return DELETE;
      default:
        return null;
    }
  }
}
