package com.youmeek.ssm.module.doc.pojo;

import java.util.Date;

public class DocumentInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_info.doc_id
     *
     * @mbggenerated
     */
    private Long docId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_info.job_id
     *
     * @mbggenerated
     */
    private Integer jobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_info.op_type
     *
     * @mbggenerated
     */
    private String opType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_info.doc_status
     *
     * @mbggenerated
     */
    private String docStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_info.doc_create_time
     *
     * @mbggenerated
     */
    private Date docCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_info.doc_modify_time
     *
     * @mbggenerated
     */
    private Date docModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_info.doc_content
     *
     * @mbggenerated
     */
    private String docContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_info.doc_id
     *
     * @return the value of document_info.doc_id
     *
     * @mbggenerated
     */
    public Long getDocId() {
        return docId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_info.doc_id
     *
     * @param docId the value for document_info.doc_id
     *
     * @mbggenerated
     */
    public void setDocId(Long docId) {
        this.docId = docId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_info.job_id
     *
     * @return the value of document_info.job_id
     *
     * @mbggenerated
     */
    public Integer getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_info.job_id
     *
     * @param jobId the value for document_info.job_id
     *
     * @mbggenerated
     */
    public void setJobId(Integer jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_info.op_type
     *
     * @return the value of document_info.op_type
     *
     * @mbggenerated
     */
    public String getOpType() {
        return opType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_info.op_type
     *
     * @param opType the value for document_info.op_type
     *
     * @mbggenerated
     */
    public void setOpType(String opType) {
        this.opType = opType == null ? null : opType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_info.doc_status
     *
     * @return the value of document_info.doc_status
     *
     * @mbggenerated
     */
    public String getDocStatus() {
        return docStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_info.doc_status
     *
     * @param docStatus the value for document_info.doc_status
     *
     * @mbggenerated
     */
    public void setDocStatus(String docStatus) {
        this.docStatus = docStatus == null ? null : docStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_info.doc_create_time
     *
     * @return the value of document_info.doc_create_time
     *
     * @mbggenerated
     */
    public Date getDocCreateTime() {
        return docCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_info.doc_create_time
     *
     * @param docCreateTime the value for document_info.doc_create_time
     *
     * @mbggenerated
     */
    public void setDocCreateTime(Date docCreateTime) {
        this.docCreateTime = docCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_info.doc_modify_time
     *
     * @return the value of document_info.doc_modify_time
     *
     * @mbggenerated
     */
    public Date getDocModifyTime() {
        return docModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_info.doc_modify_time
     *
     * @param docModifyTime the value for document_info.doc_modify_time
     *
     * @mbggenerated
     */
    public void setDocModifyTime(Date docModifyTime) {
        this.docModifyTime = docModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_info.doc_content
     *
     * @return the value of document_info.doc_content
     *
     * @mbggenerated
     */
    public String getDocContent() {
        return docContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_info.doc_content
     *
     * @param docContent the value for document_info.doc_content
     *
     * @mbggenerated
     */
    public void setDocContent(String docContent) {
        this.docContent = docContent == null ? null : docContent.trim();
    }
}